apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices-app
  namespace: argocd
spec: 
  project: default
  source: 
    #chart: onlineboutique
    repoURL: https://github.com/connellian/microservices-demo.git
    path: helm-chart
    helm:
      releaseName: onlineboutique
  destination: 
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices-app1
  namespace: argocd
spec: 
  project: default
  source: 
    #chart: onlineboutique
    repoURL: https://github.com/connellian/microservices-demo.git
    path: helm-chart
    helm:
      releaseName: onlineboutique
      valueFiles:
        - helm-chart/values1.yaml
  destination: 
    server: https://kubernetes.default.svc
    namespace: default1

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
